config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'landing_page#index'

  resources :discussion_posts

end

app/models/discussion_post.rb
class DiscussionPost < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :discussion_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/discussion_posts_controller.rb
class DiscussionPostsController < ApplicationController
	before_action :authenticate_user!

	def index
		@all_discussion_posts = DiscussionPost.includes(:user).all.order(created_at: :desc)
	end

	def show
	end

	def create # save to db
		@post = DiscussionPost.new(discussion_post_params)
		@post.user_id = current_user.id
		@post.save

		redirect_to action: 'index'
	end

	def new
		@post = DiscussionPost.new
	end

	def edit
		# GET 
	end

	def destroy
	end

	def update
		# POST
	end

	private

	def discussion_post_params
		params.require(:discussion_post).permit(:content)
	end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
	def index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/discussion_posts/index.html.erb
<h1>Our Discussion Page</h1>
<hr />
<% unless @all_discussion_posts.empty? %>
	<ul class="discussion-posts-list">
	<% @all_discussion_posts.each do |post| %>
		<li>
			<strong><%= post.user.first_name + " " + post.user.last_name %></strong>: <%= post.content %>
			<br />
			<small>- <%= post.created_at.localtime.strftime("%I:%M %p %m/%d") %></small>
		</li>

	<% end %>
	</ul>
<% end %>

app/views/discussion_posts/new.html.erb
<%= form_for @post do |f|%>
	<strong><%= f.label 'Post Content' %></strong>
	<br />
	<%= f.text_area :content, size: '100x10' %>
	<br />
	<%= f.submit %>
<% end %>

app/views/landing_page/index.html.erb
<h1>Hi There! This is the landing page.</h1>
<p>We need to figure out something better to put here...</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HandsOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if current_user %>
		<%= link_to 'Add New Post!', new_discussion_post_path %> |
		<%= link_to 'See all discussions', discussion_posts_path %> |
		<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to 'Sign In', new_user_session_path %> |
		<%= link_to 'Sign Up', new_user_registration_path %>
	<% end %>

	<hr />
	<%= yield %>

</body>
</html>